package net.beamex.shamaschizm.entity.client;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

/** The supplied Blockbench animations used by the Ciglun combat state machine. */
public final class CiglunAnimations {
    private CiglunAnimations() {}

    public static final AnimationDefinition OPEN = AnimationDefinition.Builder.withLength(6f)
    .addAnimation("brick1",
    	new AnimationChannel(AnimationChannel.Targets.POSITION, 
    		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.LINEAR), 
    		new Keyframe(0.25f, KeyframeAnimations.posVec(-8f, -4f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(0.5f, KeyframeAnimations.posVec(-16f, -8f, 8f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(0.75f, KeyframeAnimations.posVec(-16f, -8f, 16f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(1f, KeyframeAnimations.posVec(-10f, -8f, 18f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(1.5f, KeyframeAnimations.posVec(8f, -6f, 19f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2f, KeyframeAnimations.posVec(14f, -4f, 1f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2.5f, KeyframeAnimations.posVec(0f, 0f, -14f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2.75f, KeyframeAnimations.posVec(0f, 0f, -14f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(3.45833f, KeyframeAnimations.posVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("brick1",
    	new AnimationChannel(AnimationChannel.Targets.ROTATION,
    		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.LINEAR),
    		new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 90f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, 135f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 150f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 195f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 270f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2.5f, KeyframeAnimations.degreeVec(0f, 357.5f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2.75f, KeyframeAnimations.degreeVec(0f, 360f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("brick3",
    	new AnimationChannel(AnimationChannel.Targets.POSITION, 
    		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.LINEAR), 
    		new Keyframe(0.25f, KeyframeAnimations.posVec(8f, -4f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(0.5f, KeyframeAnimations.posVec(16f, -8f, -8f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(0.75f, KeyframeAnimations.posVec(16f, -8f, -16f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(1f, KeyframeAnimations.posVec(10f, -8f, -22f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(1.5f, KeyframeAnimations.posVec(-8f, -6f, -19f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2f, KeyframeAnimations.posVec(-14f, -4f, -1f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2.5f, KeyframeAnimations.posVec(0f, 0f, 14f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2.75f, KeyframeAnimations.posVec(0f, 0f, 14f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(3.54167f, KeyframeAnimations.posVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("brick3",
    	new AnimationChannel(AnimationChannel.Targets.ROTATION,
    		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.LINEAR),
    		new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 90f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, 135f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 150f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 195f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 270f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2.5f, KeyframeAnimations.degreeVec(0f, 360f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2.75f, KeyframeAnimations.degreeVec(0f, 360f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("brick2",
    	new AnimationChannel(AnimationChannel.Targets.POSITION, 
    		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.LINEAR), 
    		new Keyframe(0.25f, KeyframeAnimations.posVec(8f, 4f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(0.5f, KeyframeAnimations.posVec(16f, 8f, -8f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(0.75f, KeyframeAnimations.posVec(13f, 8f, -13f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(1f, KeyframeAnimations.posVec(6f, 8f, -14f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(1.5f, KeyframeAnimations.posVec(-10f, 6f, -6f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2f, KeyframeAnimations.posVec(-10f, 4f, 2f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2.5f, KeyframeAnimations.posVec(0f, 0f, 6f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2.75f, KeyframeAnimations.posVec(0f, 0f, 6f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(3.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("brick2",
    	new AnimationChannel(AnimationChannel.Targets.ROTATION,
    		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.LINEAR),
    		new Keyframe(0.5f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(0.75f, KeyframeAnimations.degreeVec(-135f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(1f, KeyframeAnimations.degreeVec(-165f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(1.5f, KeyframeAnimations.degreeVec(-225f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2f, KeyframeAnimations.degreeVec(-270f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2.5f, KeyframeAnimations.degreeVec(-360f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2.75f, KeyframeAnimations.degreeVec(-360f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("brick6",
    	new AnimationChannel(AnimationChannel.Targets.POSITION, 
    		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.LINEAR), 
    		new Keyframe(0.25f, KeyframeAnimations.posVec(-8f, 4f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(0.5f, KeyframeAnimations.posVec(-16f, 8f, 8f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(0.75f, KeyframeAnimations.posVec(-13f, 8f, 13f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(1f, KeyframeAnimations.posVec(-6f, 8f, 14f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(1.5f, KeyframeAnimations.posVec(10f, 6f, 6f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2f, KeyframeAnimations.posVec(10f, 4f, -2f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2.5f, KeyframeAnimations.posVec(0f, 0f, -6f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2.75f, KeyframeAnimations.posVec(0f, 0f, -6f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(3.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("brick6",
    	new AnimationChannel(AnimationChannel.Targets.ROTATION,
    		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.LINEAR),
    		new Keyframe(0.5f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(0.75f, KeyframeAnimations.degreeVec(-135f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(1f, KeyframeAnimations.degreeVec(-167.5f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(1.5f, KeyframeAnimations.degreeVec(-227.5f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2f, KeyframeAnimations.degreeVec(-272.5f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2.5f, KeyframeAnimations.degreeVec(-360f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2.75f, KeyframeAnimations.degreeVec(-360f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("brick4",
    	new AnimationChannel(AnimationChannel.Targets.POSITION, 
    		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.LINEAR), 
    		new Keyframe(0.25f, KeyframeAnimations.posVec(-6f, 0f, -6f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(0.5f, KeyframeAnimations.posVec(-12f, 0f, -8f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(0.75f, KeyframeAnimations.posVec(-18f, 0f, -2f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(1f, KeyframeAnimations.posVec(-16f, 0f, 8f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(1.5f, KeyframeAnimations.posVec(-2f, 0f, 12f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2f, KeyframeAnimations.posVec(8f, 0f, 2f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2.25f, KeyframeAnimations.posVec(1.63f, 0f, -6.12f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2.5f, KeyframeAnimations.posVec(-6f, 0f, -7f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(3f, KeyframeAnimations.posVec(-10f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(3.25f, KeyframeAnimations.posVec(-10f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(3.75f, KeyframeAnimations.posVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("brick4",
    	new AnimationChannel(AnimationChannel.Targets.ROTATION,
    		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.LINEAR),
    		new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 45f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, 90f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 135f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 180f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 240f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2.5f, KeyframeAnimations.degreeVec(0f, 295f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 360f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(3.25f, KeyframeAnimations.degreeVec(0f, 360f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("brick5",
    	new AnimationChannel(AnimationChannel.Targets.POSITION, 
    		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.LINEAR), 
    		new Keyframe(0.25f, KeyframeAnimations.posVec(6f, 0f, 6f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(0.5f, KeyframeAnimations.posVec(12f, 0f, 8f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(0.75f, KeyframeAnimations.posVec(18f, 0f, 2f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(1f, KeyframeAnimations.posVec(16f, 0f, -8f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(1.5f, KeyframeAnimations.posVec(2f, 0f, -12f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2f, KeyframeAnimations.posVec(-8f, 0f, -2f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2.25f, KeyframeAnimations.posVec(-1.62f, 0f, 4.13f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2.5f, KeyframeAnimations.posVec(6f, 0f, 7f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(3f, KeyframeAnimations.posVec(10f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(3.20833f, KeyframeAnimations.posVec(10f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(3.79167f, KeyframeAnimations.posVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("brick5",
    	new AnimationChannel(AnimationChannel.Targets.ROTATION,
    		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.LINEAR),
    		new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 45f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, 90f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 135f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 180f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 237.5f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2.5f, KeyframeAnimations.degreeVec(0f, 295f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 365f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(3.20833f, KeyframeAnimations.degreeVec(0f, 360f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("oko",
    	new AnimationChannel(AnimationChannel.Targets.ROTATION,
    		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.LINEAR),
    		new Keyframe(0.29167f, KeyframeAnimations.degreeVec(0f, 0f, 90f),
    			AnimationChannel.Interpolations.LINEAR),
    		new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 0f, 1260f),
    			AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("brick7",
    	new AnimationChannel(AnimationChannel.Targets.POSITION, 
    		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(0.25f, KeyframeAnimations.posVec(-6f, 0f, 6f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(0.5f, KeyframeAnimations.posVec(-8f, 0f, 12f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(0.75f, KeyframeAnimations.posVec(-2f, 0f, 16f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(1f, KeyframeAnimations.posVec(4f, 0f, 16f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(1.5f, KeyframeAnimations.posVec(16f, 0f, 8f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2f, KeyframeAnimations.posVec(16f, 0f, -6f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2.5f, KeyframeAnimations.posVec(7f, 0f, -14f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(3f, KeyframeAnimations.posVec(-11f, 0f, -8f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(3.5f, KeyframeAnimations.posVec(-11f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(3.70833f, KeyframeAnimations.posVec(-11f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(4.29167f, KeyframeAnimations.posVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("brick7",
    	new AnimationChannel(AnimationChannel.Targets.ROTATION,
    		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 45f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, 75f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 95f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 155f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 195f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2.5f, KeyframeAnimations.degreeVec(0f, 250f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 335f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(3.5f, KeyframeAnimations.degreeVec(0f, 360f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(3.70833f, KeyframeAnimations.degreeVec(0f, 360f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("brick8",
    	new AnimationChannel(AnimationChannel.Targets.POSITION, 
    		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(0.25f, KeyframeAnimations.posVec(6f, 0f, -6f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(0.5f, KeyframeAnimations.posVec(8f, 0f, -12f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(0.75f, KeyframeAnimations.posVec(2f, 0f, -16f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(1.5f, KeyframeAnimations.posVec(-16f, 0f, -8f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2f, KeyframeAnimations.posVec(-16f, 0f, 6f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2.5f, KeyframeAnimations.posVec(-7f, 0f, 14f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(3f, KeyframeAnimations.posVec(11f, 0f, 8f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(3.5f, KeyframeAnimations.posVec(11f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(3.75f, KeyframeAnimations.posVec(11f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(4.29167f, KeyframeAnimations.posVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("brick8",
    	new AnimationChannel(AnimationChannel.Targets.ROTATION,
    		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 45f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, 75f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 155f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 195f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2.5f, KeyframeAnimations.degreeVec(0f, 250f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 335f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(3.5f, KeyframeAnimations.degreeVec(0f, 365f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(3.75f, KeyframeAnimations.degreeVec(0f, 360f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM))).build();
    public static final AnimationDefinition TURNSAROUND2 = AnimationDefinition.Builder.withLength(5.75f)
    .addAnimation("brick1",
    	new AnimationChannel(AnimationChannel.Targets.POSITION, 
    		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.LINEAR), 
    		new Keyframe(0.25f, KeyframeAnimations.posVec(-8f, -4f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(0.5f, KeyframeAnimations.posVec(-16f, -8f, 8f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(0.75f, KeyframeAnimations.posVec(-16f, -8f, 16f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(1f, KeyframeAnimations.posVec(-10f, -8f, 18f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(1.5f, KeyframeAnimations.posVec(8f, -6f, 19f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2f, KeyframeAnimations.posVec(14f, -4f, 1f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2.5f, KeyframeAnimations.posVec(0f, 0f, -14f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2.75f, KeyframeAnimations.posVec(0f, 0f, -14f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(3.45833f, KeyframeAnimations.posVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("brick1",
    	new AnimationChannel(AnimationChannel.Targets.ROTATION,
    		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.LINEAR),
    		new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 90f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, 135f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 150f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 195f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 270f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2.5f, KeyframeAnimations.degreeVec(0f, 357.5f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2.75f, KeyframeAnimations.degreeVec(0f, 360f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("brick3",
    	new AnimationChannel(AnimationChannel.Targets.POSITION, 
    		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.LINEAR), 
    		new Keyframe(0.25f, KeyframeAnimations.posVec(8f, -4f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(0.5f, KeyframeAnimations.posVec(16f, -8f, -8f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(0.75f, KeyframeAnimations.posVec(16f, -8f, -16f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(1f, KeyframeAnimations.posVec(10f, -8f, -22f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(1.5f, KeyframeAnimations.posVec(-8f, -6f, -19f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2f, KeyframeAnimations.posVec(-14f, -4f, -1f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2.5f, KeyframeAnimations.posVec(0f, 0f, 14f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2.75f, KeyframeAnimations.posVec(0f, 0f, 14f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(3.54167f, KeyframeAnimations.posVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("brick3",
    	new AnimationChannel(AnimationChannel.Targets.ROTATION,
    		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.LINEAR),
    		new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 90f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, 135f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 150f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 195f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 270f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2.5f, KeyframeAnimations.degreeVec(0f, 360f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2.75f, KeyframeAnimations.degreeVec(0f, 360f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("brick2",
    	new AnimationChannel(AnimationChannel.Targets.POSITION, 
    		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.LINEAR), 
    		new Keyframe(0.25f, KeyframeAnimations.posVec(8f, 4f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(0.5f, KeyframeAnimations.posVec(16f, 8f, -8f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(0.75f, KeyframeAnimations.posVec(13f, 8f, -13f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(1f, KeyframeAnimations.posVec(6f, 8f, -14f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(1.5f, KeyframeAnimations.posVec(-10f, 6f, -6f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2f, KeyframeAnimations.posVec(-10f, 4f, 2f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2.5f, KeyframeAnimations.posVec(0f, 0f, 6f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2.75f, KeyframeAnimations.posVec(0f, 0f, 6f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(3.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("brick2",
    	new AnimationChannel(AnimationChannel.Targets.ROTATION,
    		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.LINEAR),
    		new Keyframe(0.5f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(0.75f, KeyframeAnimations.degreeVec(-135f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(1f, KeyframeAnimations.degreeVec(-165f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(1.5f, KeyframeAnimations.degreeVec(-225f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2f, KeyframeAnimations.degreeVec(-270f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2.5f, KeyframeAnimations.degreeVec(-360f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2.75f, KeyframeAnimations.degreeVec(-360f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("brick6",
    	new AnimationChannel(AnimationChannel.Targets.POSITION, 
    		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.LINEAR), 
    		new Keyframe(0.25f, KeyframeAnimations.posVec(-8f, 4f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(0.5f, KeyframeAnimations.posVec(-16f, 8f, 8f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(0.75f, KeyframeAnimations.posVec(-13f, 8f, 13f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(1f, KeyframeAnimations.posVec(-6f, 8f, 14f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(1.5f, KeyframeAnimations.posVec(10f, 6f, 6f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2f, KeyframeAnimations.posVec(10f, 4f, -2f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2.5f, KeyframeAnimations.posVec(0f, 0f, -6f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2.75f, KeyframeAnimations.posVec(0f, 0f, -6f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(3.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("brick6",
    	new AnimationChannel(AnimationChannel.Targets.ROTATION,
    		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.LINEAR),
    		new Keyframe(0.5f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(0.75f, KeyframeAnimations.degreeVec(-135f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(1f, KeyframeAnimations.degreeVec(-167.5f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(1.5f, KeyframeAnimations.degreeVec(-227.5f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2f, KeyframeAnimations.degreeVec(-272.5f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2.5f, KeyframeAnimations.degreeVec(-360f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2.75f, KeyframeAnimations.degreeVec(-360f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("brick4",
    	new AnimationChannel(AnimationChannel.Targets.POSITION, 
    		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.LINEAR), 
    		new Keyframe(0.25f, KeyframeAnimations.posVec(-6f, 0f, -6f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(0.5f, KeyframeAnimations.posVec(-12f, 0f, -8f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(0.75f, KeyframeAnimations.posVec(-18f, 0f, -2f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(1f, KeyframeAnimations.posVec(-16f, 0f, 8f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(1.5f, KeyframeAnimations.posVec(-2f, 0f, 12f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2f, KeyframeAnimations.posVec(8f, 0f, 2f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2.25f, KeyframeAnimations.posVec(1.63f, 0f, -6.12f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2.5f, KeyframeAnimations.posVec(-6f, 0f, -7f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(3f, KeyframeAnimations.posVec(-10f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(3.25f, KeyframeAnimations.posVec(-10f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(3.75f, KeyframeAnimations.posVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("brick4",
    	new AnimationChannel(AnimationChannel.Targets.ROTATION,
    		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.LINEAR),
    		new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 45f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, 90f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 135f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 180f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 240f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2.5f, KeyframeAnimations.degreeVec(0f, 295f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 360f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(3.25f, KeyframeAnimations.degreeVec(0f, 360f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("brick5",
    	new AnimationChannel(AnimationChannel.Targets.POSITION, 
    		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.LINEAR), 
    		new Keyframe(0.25f, KeyframeAnimations.posVec(6f, 0f, 6f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(0.5f, KeyframeAnimations.posVec(12f, 0f, 8f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(0.75f, KeyframeAnimations.posVec(18f, 0f, 2f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(1f, KeyframeAnimations.posVec(16f, 0f, -8f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(1.5f, KeyframeAnimations.posVec(2f, 0f, -12f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2f, KeyframeAnimations.posVec(-8f, 0f, -2f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2.25f, KeyframeAnimations.posVec(-1.62f, 0f, 4.13f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2.5f, KeyframeAnimations.posVec(6f, 0f, 7f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(3f, KeyframeAnimations.posVec(10f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(3.20833f, KeyframeAnimations.posVec(10f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(3.79167f, KeyframeAnimations.posVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("brick5",
    	new AnimationChannel(AnimationChannel.Targets.ROTATION,
    		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.LINEAR),
    		new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 45f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, 90f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 135f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 180f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 237.5f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2.5f, KeyframeAnimations.degreeVec(0f, 295f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 365f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(3.20833f, KeyframeAnimations.degreeVec(0f, 360f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("oko",
    	new AnimationChannel(AnimationChannel.Targets.ROTATION,
    		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.LINEAR),
    		new Keyframe(0.29167f, KeyframeAnimations.degreeVec(0f, 0f, 90f),
    			AnimationChannel.Interpolations.LINEAR),
    		new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 0f, 1260f),
    			AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("brick7",
    	new AnimationChannel(AnimationChannel.Targets.POSITION, 
    		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(0.25f, KeyframeAnimations.posVec(-6f, 0f, 6f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(0.5f, KeyframeAnimations.posVec(-8f, 0f, 12f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(0.75f, KeyframeAnimations.posVec(-2f, 0f, 16f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(1f, KeyframeAnimations.posVec(4f, 0f, 16f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(1.5f, KeyframeAnimations.posVec(16f, 0f, 8f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2f, KeyframeAnimations.posVec(16f, 0f, -6f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2.5f, KeyframeAnimations.posVec(7f, 0f, -14f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(3f, KeyframeAnimations.posVec(-11f, 0f, -8f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(3.5f, KeyframeAnimations.posVec(-11f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(3.70833f, KeyframeAnimations.posVec(-11f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(4.29167f, KeyframeAnimations.posVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("brick7",
    	new AnimationChannel(AnimationChannel.Targets.ROTATION,
    		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 45f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, 75f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 95f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 155f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 195f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2.5f, KeyframeAnimations.degreeVec(0f, 250f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 335f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(3.5f, KeyframeAnimations.degreeVec(0f, 360f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(3.70833f, KeyframeAnimations.degreeVec(0f, 360f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("brick8",
    	new AnimationChannel(AnimationChannel.Targets.POSITION, 
    		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(0.25f, KeyframeAnimations.posVec(6f, 0f, -6f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(0.5f, KeyframeAnimations.posVec(8f, 0f, -12f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(0.75f, KeyframeAnimations.posVec(2f, 0f, -16f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(1.5f, KeyframeAnimations.posVec(-16f, 0f, -8f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2f, KeyframeAnimations.posVec(-16f, 0f, 6f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2.5f, KeyframeAnimations.posVec(-7f, 0f, 14f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(3f, KeyframeAnimations.posVec(11f, 0f, 8f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(3.5f, KeyframeAnimations.posVec(11f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(3.75f, KeyframeAnimations.posVec(11f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(4.29167f, KeyframeAnimations.posVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("brick8",
    	new AnimationChannel(AnimationChannel.Targets.ROTATION,
    		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 45f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, 75f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 155f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 195f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(2.5f, KeyframeAnimations.degreeVec(0f, 250f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 335f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(3.5f, KeyframeAnimations.degreeVec(0f, 365f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(3.75f, KeyframeAnimations.degreeVec(0f, 360f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("glava",
    	new AnimationChannel(AnimationChannel.Targets.POSITION, 
    		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 10f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(3.75f, KeyframeAnimations.posVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("glava",
    	new AnimationChannel(AnimationChannel.Targets.ROTATION,
    		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(1f, KeyframeAnimations.degreeVec(90f, 0f, 192.5f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(3f, KeyframeAnimations.degreeVec(180f, 0f, 360f),
    			AnimationChannel.Interpolations.CATMULLROM),
    		new Keyframe(4.95833f, KeyframeAnimations.degreeVec(-360f, 180f, 720f),
    			AnimationChannel.Interpolations.CATMULLROM))).build();
    public static final AnimationDefinition IDLE = AnimationDefinition.Builder.withLength(5f).looping()
    .addAnimation("glava",
    	new AnimationChannel(AnimationChannel.Targets.POSITION, 
    		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(2.5f, KeyframeAnimations.posVec(0f, 0.4f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM), 
    		new Keyframe(4.91667f, KeyframeAnimations.posVec(0f, 0f, 0f),
    			AnimationChannel.Interpolations.CATMULLROM))).build();
}

