package net.beamex.shamaschizm.entity.client;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

/** Exact supplied 6.125-second Blockbench opening animation. */
public final class MegalithicGateAnimations {
private MegalithicGateAnimations() {}

public static final AnimationDefinition OPEN = AnimationDefinition.Builder.withLength(6.125f)
.addAnimation("bone",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.125f, KeyframeAnimations.posVec(0f, 1f, -0.5f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.25f, KeyframeAnimations.posVec(0f, 2f, 0.5f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.375f, KeyframeAnimations.posVec(0f, 3f, -0.5f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 4f, 0.7f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.625f, KeyframeAnimations.posVec(0f, 5f, -0.2f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 6f, 0.5f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.875f, KeyframeAnimations.posVec(0f, 7f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(1f, KeyframeAnimations.posVec(0f, 8f, 0.3f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(1.125f, KeyframeAnimations.posVec(0f, 9f, 0.5f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(1.25f, KeyframeAnimations.posVec(0f, 10f, 1f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(1.4167667f, KeyframeAnimations.posVec(0f, 12f, -0.5f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(1.5416767f, KeyframeAnimations.posVec(0f, 13f, 0.1f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(1.6766667f, KeyframeAnimations.posVec(0f, 13f, -0.3f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(1.7916767f, KeyframeAnimations.posVec(0f, 14f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(1.9167667f, KeyframeAnimations.posVec(0f, 14f, -0.4f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(2.0416765f, KeyframeAnimations.posVec(0f, 14f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(2.1676665f, KeyframeAnimations.posVec(0f, 16f, -0.5f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(2.2916765f, KeyframeAnimations.posVec(0f, 17f, 0.5f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(2.4167665f, KeyframeAnimations.posVec(0f, 18f, -0.5f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(2.5416765f, KeyframeAnimations.posVec(0f, 19f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(2.6766665f, KeyframeAnimations.posVec(0f, 20f, 0.2f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(2.7916765f, KeyframeAnimations.posVec(0f, 21f, -0.5f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(2.9167665f, KeyframeAnimations.posVec(0f, 22f, 0.5f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(3.0416765f, KeyframeAnimations.posVec(0f, 23f, -0.1f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(3.1676665f, KeyframeAnimations.posVec(0f, 24f, 0.2f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(3.2916765f, KeyframeAnimations.posVec(0f, 25f, -0.5f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(3.4167665f, KeyframeAnimations.posVec(0f, 26f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(3.5416765f, KeyframeAnimations.posVec(0f, 27f, 1.5f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(3.6766665f, KeyframeAnimations.posVec(0f, 28f, 1f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(3.7916765f, KeyframeAnimations.posVec(0f, 29f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(3.9167665f, KeyframeAnimations.posVec(0f, 30f, -0.5f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(4.041677f, KeyframeAnimations.posVec(0f, 31f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(4.167667f, KeyframeAnimations.posVec(0f, 32f, 0.5f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(4.291677f, KeyframeAnimations.posVec(0f, 33f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(4.416767f, KeyframeAnimations.posVec(0f, 34f, 0.6f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(4.541677f, KeyframeAnimations.posVec(0f, 35f, -0.2f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(4.676667f, KeyframeAnimations.posVec(0f, 36f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(4.791677f, KeyframeAnimations.posVec(0f, 38f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(4.916767f, KeyframeAnimations.posVec(0f, 39f, 0.5f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(5.041677f, KeyframeAnimations.posVec(0f, 39f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(5.167667f, KeyframeAnimations.posVec(0f, 40f, -0.5f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(5.291677f, KeyframeAnimations.posVec(0f, 40f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(5.416767f, KeyframeAnimations.posVec(0f, 41f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(5.541677f, KeyframeAnimations.posVec(0f, 42f, -0.5f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(5.676667f, KeyframeAnimations.posVec(0f, 42f, 0.3f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(5.791677f, KeyframeAnimations.posVec(0f, 43f, 0.5f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(5.958343f, KeyframeAnimations.posVec(0f, 44f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(6.125f, KeyframeAnimations.posVec(0f, 45f, 0f),
			AnimationChannel.Interpolations.LINEAR))).build();
}
